### ISSUE TITLE
Unable to resolve service "MyLogger" to a factory

### ISSUE THREAD

**Issue by MyUncleSam** [chrRtg/eve-skylizer#2]
Hi there,

I tried to install it using your installation guide but after I successfully executed all steps I only get this error by trying to open the page. Can you help me please? The region about MyLogger was not touched by me.

Some information:
- tried php 7.0 and 7.1 (both with installed gd and intl)
- fetched code using git clone
- also did a composer update whcih updated quite a lot packages - but still not working

`
Fatal error: Uncaught Zend\ServiceManager\Exception\ServiceNotFoundException: Unable to resolve service "MyLogger" to a factory; are you certain you provided it during configuration? in /var/www/virtual/evepage.space/scan/htdocs/eve-skylizer/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:681
Stack trace:
#0 /var/www/virtual/evepage.space/scan/htdocs/eve-skylizer/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(757): Zend\ServiceManager\ServiceManager->getFactory('MyLogger')
#1 /var/www/virtual/evepage.space/scan/htdocs/eve-skylizer/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(200): Zend\ServiceManager\ServiceManager->doCreate('MyLogger')
#2 /var/www/virtual/evepage.space/scan/htdocs/eve-skylizer/module/User/src/Service/Factory/UserManagerFactory.php(24): Zend\ServiceManager\ServiceManager->get('MyLogger')
#3 /var/www/virtual/evepage.space/scan/htdocs/eve-skylizer/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(758): User\Service\Factory\UserManagerFactory- in /var/www/virtual/evepage.space/scan/htdocs/eve-skylizer/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 681
`

**Comment by MyUncleSam** [comment]
Never mind, solved it by cleaning the cache. Some old config file (which was broken) was cached and used instead of the working one ...
