### ISSUE TITLE
User\Service\EveSSOManager could not be created

### ISSUE THREAD

**Issue by andymelichar** [chrRtg/eve-skylizer#37]
Fresh install on Ubuntu 18 / nginx / PHP 7.4

`Service with name "User\Service\EveSSOManager" could not be created. Reason: Session validation failed`

File: /var/www/skylizer/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:771

`#0 /var/www/skylizer/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(200): Zend\ServiceManager\ServiceManager->doCreate()
#1 /var/www/skylizer/module/User/src/Module.php(59): Zend\ServiceManager\ServiceManager->get()
#2 /var/www/skylizer/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): User\Module->onDispatch()
#3 /var/www/skylizer/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners()
#4 /var/www/skylizer/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(104): Zend\EventManager\EventManager->triggerEventUntil()
#5 /var/www/skylizer/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch()
#6 /var/www/skylizer/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch()
#7 /var/www/skylizer/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners()
#8 /var/www/skylizer/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil()
#9 /var/www/skylizer/public/index.php(40): Zend\Mvc\Application->run()
#10 {main}`

**Comment by andymelichar** [comment]
An update, clearing cookies and adding `'use_cookies'     => true,` to global.php seems to help, but now the issue I'm dealing with is when I'm sent over to Eve for SSO, when I click Authorize, it just keeps redirecting me back to the same Eve SSO screen with the Authorize button.

**Comment by andymelichar** [comment]
Turns out my issue was Cloudflare. Because symfony checks the IP address as part of the IP validation, every time the IP address from Cloudflare changed (quite often) the session would fail to validate and the above error would happen.

The solution is to install mod_cloudflare into Apache, so that apache presents the actual user IP to symfony. No more session validation errors.
